GET http://localhost:5000/users
Authorization: Bearer
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJBbm9ueW1vdXMiLCJlbWFpbCI6ImFub255bW91c0BnbWFpbC5jb20iLCJpYXQiOjE3MzIwODQwMzksImV4cCI6MTczMjA4NDA1NH0.o-JxQKx7fXadOoeCes0FGl-MBn-f0qBIpSc-pfDfee8

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Anonymous",
    "email": "anonymous@gmail.com",
    "password": "123456",
    "confPassword": "123456"
}

###

POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "anonymous@gmail.com",
    "password": "123456"
}

###
GET http://localhost:5000/token

###
DELETE http://localhost:5000/logout